services:
  singularity:
    # 1. IMAGEN (LOCAL v1.6)
    image: rawsmoke/singularity-suite:latest
    container_name: singularity_core
    restart: unless-stopped
    privileged: true
    user: "${PUID:-1000}:${PGID:-1000}"
    group_add:
      - "997"         # Acceso directo al grupo 'render' (AMD/Intel)
      - "107"         # Por si acaso, el grupo 'video' en algunos RHEL
    env_file: ./config/.env
    command: bash -c "python3 -m core.dashboard & tail -f /dev/null"
    environment:
      - TZ=Europe/Madrid
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - LIBVA_DRIVER_NAME=radeonsi # Fuerza el driver de AMD
    devices:
      - /dev/dri:/dev/dri # Mapeo explícito del hardware gráfico
      - /dev/fb0:/dev/fb0 # Framebuffer (opcional pero ayuda en probes)

    deploy:
      resources:
        limits:
          cpus: '6.0'
          memory: 8G

    # 3. VOLÚMENES RE-ALINEADOS
    volumes:
      # --- 1. CONFIGURACIÓN (Mantenemos montajes de archivos para estabilidad de 'make') ---
      - ./config/.env:/app/.env:z
      - ./config/singularity_config.py:/app/singularity_config.py:z
      - ./config/config.py:/app/RawLoadrr/data/config.py:z
      - ./config/mass_config.py:/app/extras/MASS-EDITION-UNIT3D/config.py:z
#      - ./clean_vs_bad_descriptions.txt:/app/clean_vs_bad_descriptions.txt:z
#      - ./leftover_pixhost_dirs.txt:/app/leftover_pixhost_dirs.txt:z

      # --- 2. WORK DATA & PERSISTENCIA ---
      - ./work_data/mass_editor/ids.txt:/app/extras/MASS-EDITION-UNIT3D/ids.txt:z
      - ./work_data/mass_editor/completados.txt:/app/extras/MASS-EDITION-UNIT3D/completados.txt:z
      - ./work_data/mass_editor/completados_img.txt:/app/extras/MASS-EDITION-UNIT3D/completados_img.txt:z
      - ./work_data/mass_editor/mapeo_maestro.json:/app/extras/MASS-EDITION-UNIT3D/mapeo_maestro.json:z
      - ./work_data/tmp:/app/RawLoadrr/tmp:z
      - ./work_data/logs:/app/logs:z
      - ./work_data/reports:/app/MKVerything/docs:z
      - ./work_data/trackers:/app/RawLoadrr/src/trackers:z
      - ./work_data/reports:/app/work_data/reports:z
      
      # --- 3. CSI LOGS (Exponemos la carpeta del CSI para debug real) ---
      - ./work_data/logs/csi_log:/app/extras/CSI/csi_log:z

      # --- 4. EL ARSENAL (30TB) ---
      - /run/media/${USER}:/run/media/${USER}:z
      - ${HOME}:${HOME}:z

    network_mode: host
    stdin_open: true
    tty: true
